alias home='git --work-tree=$HOME --git-dir=$HOME/.home'
alias docs='cd ~/Documents'
alias downloads='cd ~/Downloads'
alias work='cd ~/WorkBench'
alias gith='cd ~/WorkBench/GitHub'
alias dat='cd ~/WorkBench/sandbox/analysis && source ~/WorkBench/pyenvs/analysis-env/bin/activate && touch tmp.ipynb && code tmp.ipynb'
alias san='cd ~/WorkBench/sandbox'
alias python='python3'
alias youtube-dl='python3 $(which youtube-dl)'
alias copy='xclip -selection clipboard <'
