# awesome
# Autogenerated from man page /usr/share/man/man1/awesome.1.gz
complete -c awesome -s v -l version --description '.'
complete -c awesome -s h -l help --description '.'
complete -c awesome -s c -l config --description '.'
complete -c awesome -s k -l check --description '.'
complete -c awesome -l search --description '.'
complete -c awesome -s a -l no-argb --description '.'
complete -c awesome -s r -l replace --description '.'

