# gdm3
# Autogenerated from man page /usr/share/man/man8/gdm3.8.gz
complete -c gdm3 -s h -l help --description 'Show help options.'
complete -c gdm3 -l help-all --description 'Show all help options.'
complete -c gdm3 -l help-gtk --description 'Show \\s-1GTK+\\s0 Options . PP Application Options:.'
complete -c gdm3 -s d -l debug --description 'Debugging output.'

