# vboxheadless
# Autogenerated from man page /usr/share/man/man1/vboxheadless.1.gz
complete -c vboxheadless -s s -o startvm -l startvm --description 'Start given VM (required argument).'
complete -c vboxheadless -s v -o vrde -l vrde --description 'Enable or disable the VRDE server or don\'t change the setting (default).'
complete -c vboxheadless -s e -o vrdeproperty -l vrdeproperty --description '"TCP/Ports" - comma-separated list of.'
complete -c vboxheadless -l settingspw --description 'Specify the settings password.'
complete -c vboxheadless -l settingspwfile --description 'Specify a file containing the settings password.'
complete -c vboxheadless -o start-paused -l start-paused --description 'Start the VM in paused state.'
complete -c vboxheadless -s c -o record -l record --description 'Record the VM screen output to a file.'
complete -c vboxheadless -s w -l videowidth --description 'Video frame width when recording.'
complete -c vboxheadless -s h -l videoheight --description 'Video frame height when recording.'
complete -c vboxheadless -s r -l videobitrate --description 'Recording bit rate when recording.'
complete -c vboxheadless -s f -l filename --description 'File name when recording.'

