# x-window-manager
# Autogenerated from man page /usr/share/man/man1/x-window-manager.1.gz
complete -c x-window-manager -s v -l version --description '.'
complete -c x-window-manager -s h -l help --description '.'
complete -c x-window-manager -s c -l config --description '.'
complete -c x-window-manager -s k -l check --description '.'
complete -c x-window-manager -l search --description '.'
complete -c x-window-manager -s a -l no-argb --description '.'
complete -c x-window-manager -s r -l replace --description '.'

