# zeal
# Autogenerated from man page /usr/share/man/man1/zeal.1.gz
complete -c zeal -s h -l help --description 'Displays this help.'
complete -c zeal -s v -l version --description 'Displays version information.'
complete -c zeal -s q -l query --description 'Query _search term_.'
complete -c zeal -s f -l force --description 'Force the application run.  AUTHOR.'

