# ~/.config/starship.toml
add_newline = false

format = """ 
[┌───────────────────](bold green) $time 
[│](bold green)$charging_symbol$battery$cmd_duration $directory\
                $git_branch$git_commit$git_state$git_status$python
$character
"""

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 50
style = "bold red"

[character]
format = """[└─>](bold green) """

[cmd_duration]
min_time = 1000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[directory]
truncation_length = 5
format = "[$path]($style)[$lock_symbol]($lock_style)"

[git_branch]
format = "[ $symbol$branch]($style) "
style = "bold yellow"

[git_commit]
commit_hash_length = 8
style = "bold white"

[git_state]
progress_divider = " of "


[hostname]
ssh_only = false
format = "<[$hostname]($style)>"
trim_at = "-"
style = "bold dimmed white"
disabled = true

[memory_usage]
format = "$symbol[${ram}( | ${swap})]($style) "
show_percentage = true
show_swap = true
threshold = 50
style = "bold dimmed white"
disabled = false

[package]
disabled = true

[python]
format = "[$symbol$version]($style) "
style = "bold green"

[time]
time_format = "%T"
format = "$time($style) "
style = "bright-white"
disabled = false

[username]
style_user = "bold dimmed blue"
show_always = false
