source $HOME/.config/nvim/vim-plug/plugins.vim
source $HOME/.config/nvim/general/settings.vim
source $HOME/.config/nvim/keys/mappings.vim
source $HOME/.config/nvim/themes/onedark.vim
source $HOME/.config/nvim/plug-config/coc.vim
source $HOME/.config/nvim/plug-config/search.vim
source $HOME/.config/nvim/plug-config/start.vim
source $HOME/.config/nvim/themes/airline.vim
source $HOME/.config/nvim/plug-config/codi.vim
